spring:
  profiles:
    active: local

  server:
    port: 8080

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  task:
    scheduling:
      pool:
        size: 10

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

  redis:
    host: localhost
    port: 6379

logging:
  level:
    org:
      hibernate:
