spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
        #show_sql: true
        #format_sql: false
        #highlight_sql: false
        #use_sql_comments: true

  redis:
    host: localhost
    port: 6379

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: us-east-2
    stack:
      auto: false
    s3:
      bucket: zinoshop

jwt:
  secretKey: ${JWT_SECRET_KEY}
  accessExpire: 1800000
  refreshExpire: 186400000

toss:
  client-key: ${TOSS_CLIENT_KEY}
  secret-key: ${TOSS_SECRET_KEY}
