name: Set Environment Variables

on:
  push:
    branches:
      - main

jobs:
  set-env-vars:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 소스 코드 체크아웃

      - name: Set environment variables from secrets
        run: |
          # GitHub Secrets에서 값을 읽어 환경 변수로 설정
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> $GITHUB_ENV
          echo "TOSS_CLIENT_KEY=${{ secrets.TOSS_CLIENT_KEY }}" >> $GITHUB_ENV
          echo "TOSS_SECRET_KEY=${{ secrets.TOSS_SECRET_KEY }}" >> $GITHUB_ENV
          
      - name: Display environment variables
        run: |
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "JWT_SECRET_KEY: $JWT_SECRET_KEY"
          echo "TOSS_CLIENT_KEY: $TOSS_CLIENT_KEY"
